name: week 1

on:
 push:
 workflow_dispatch:

jobs:
      date:
            runs-on: self-hosted
            steps:
            - name: today date
              run: date
      pwd:
            runs-on: self-hosted
            needs: date
            steps:
            - name: show present dir  
              run: pwd
      branch_name:
            runs-on: self-hosted
            needs: pwd
            steps:
            - name: print baranch names  
              run: echo $GITHUB_REF

